### ISSUE TITLE
overrides gt/gT

### ISSUE THREAD

**Issue by chalmagean** [christoomey/vim-titlecase#1]
Is there a way to remove those keybindings or replace them with something else ?

**Comment by huyz** [comment]
This issue doesn't look applicable anymore. Close?

**Comment by christoomey** [comment]
Thanks for the bump here, @huyz

**Comment by mangelozzi** [comment]
I didnt understand the updated README, but looking at the code it checks if a key is registered `<Plug>Titlecase"` and `<Plug>TitlecaseLine` for the two commands, if not registers gz/gZ. So if you dont want these mapping just your own mappings before the plugin is loaded, e.g. with Neovim:

```
        vim.keymap.set({"n", "x"}, "gh", "<Plug>Titlecase", {noremap = true, desc = "Titlecase operator"})
        vim.keymap.set("n", "gH", "<Plug>TitlecaseLine", {noremap = true, desc = "Titlecase operator line"})
```

Ps thanks for the plugin (at the greate talk on how to speak the vim language)!
