### ISSUE TITLE
[FR] Add and option to unmap the default keys.

### ISSUE THREAD

**Issue by Archie-2021** [christoomey/vim-titlecase#18]
I found this closed issue here: https://github.com/christoomey/vim-titlecase/issues/1
I want to bind it to gt and gT and it is working fine. The only problem is that now I have to keys for the same function so I wish to unbind `gz` for something else. So an option to just unmap all the default keys would be very appreciated.

Thanks

**Comment by christoomey** [comment]
Hmm, are you sure there is still a mapping set for `gz`? [The plugin checks if you've defined your own mapping](https://github.com/christoomey/vim-titlecase/blob/69a697c54a08ca5603cb757b4d4f78cd4b567549/plugin/titlecase.vim#L15) and should only map `gz` if you _haven't_ mapped `<Plug>Titlecase` yourself.

**Comment by Archie-2021** [comment]
> Hmm, are you sure there is still a mapping set for `gz`? [The plugin checks if you've defined your own mapping](https://github.com/christoomey/vim-titlecase/blob/69a697c54a08ca5603cb757b4d4f78cd4b567549/plugin/titlecase.vim#L15) and should only map `gz` if you _haven't_ mapped `<Plug>Titlecase` yourself.

Now that I check it again it is working as you said. I thought I had already checked for this at the time, apparently I forgot. 

Thanks
