### ISSUE TITLE
Improper capitalization of contractions

### ISSUE THREAD

**Issue by christoomey** [christoomey/vim-titlecase#3]
"foo bar don't baz" currently titlecases as "Foo Bar **Don'T** Baz"

**Comment by chenoweth** [comment]
I think it could be fixed by adding a concat inside the regex matching a word to capitalize:

Currently it's:

    let WORD_PATTERN = '\<\(\k\)\(\k*\)\>'

It could be replaced by:

    let WORD_PATTERN = '\v''@<!&<(\k)(\k*)>'
